function catalog = pd_output_option_catalog(defaultDirectory)
%PD_OUTPUT_OPTION_CATALOG Editable output and automatic-export settings.

    if nargin < 1 || isempty(defaultDirectory)
        exportDir = fileparts(mfilename('fullpath'));
        sourceDir = fileparts(exportDir);
        projectRoot = fileparts(sourceDir);
        defaultDirectory = fullfile(projectRoot, 'outputs');
    end
    catalog = [ ...
        item('Directory', defaultDirectory, 'text', 'Output directory'), ...
        item('Prefix', 'postdata', 'text', 'Output file prefix'), ...
        item('SaveMAT', true, 'logical', 'Save the complete result structure'), ...
        item('SaveCSV', true, 'logical', 'Save scalar result summary'), ...
        item('SaveDetailCSV', false, 'logical', 'Save analysis-specific array tables'), ...
        item('SavePNG', true, 'logical', 'Save the displayed plot'), ...
        item('SaveFIG', false, 'logical', 'Save an editable MATLAB figure'), ...
        item('SavePDF', false, 'logical', 'Save the displayed plot as PDF'), ...
        item('SaveManifest', true, 'logical', 'Save reproducibility manifest'), ...
        item('DPI', 300, 'numeric', 'PNG resolution; 300 or 600 is recommended for papers'), ...
        item('FigureWidthCm', 18, 'numeric', 'Exported figure width in centimeters'), ...
        item('FigureHeightCm', 12, 'numeric', 'Exported figure height in centimeters'), ...
        item('AutoExport', false, 'logical', 'Export automatically after analysis')];
end

function value = item(name, defaultValue, typeName, description)
    value = struct('Name', name, 'Default', defaultValue, 'Type', typeName, ...
        'Target', 'output', 'Description', description);
end
