function catalog = pd_plot_option_catalog()
%PD_PLOT_OPTION_CATALOG Paper-grade editable renderer settings.

    catalog = [ ...
        item('UpdateMode', 'replace', 'text', 'Replace or overlay existing data', {'replace','overlay'}), ...
        item('ColorPalette', 'colorblind', 'text', 'Curve/bar palette', {'colorblind','lines','grayscale','highcontrast'}), ...
        item('CustomColorOrder', [], 'numeric', ...
            'Optional N-by-3 RGB color order in the range 0 to 1'), ...
        item('SeriesStyleMode', 'color-and-style', 'text', ...
            'How multiple series are distinguished', ...
            {'color','color-and-style','monochrome'}), ...
        item('Colormap', 'parula', 'text', 'Field colormap', ...
            {'parula','jet','hsv','hot','cool','spring','summer','autumn', ...
             'winter','gray','bone','copper','pink','lines','colorcube','prism','flag','white'}), ...
        item('FieldRenderMode', 'auto', 'text', ...
            '2D field renderer; auto uses an image for rectangular grids', ...
            {'auto','image','scatter','contour'}), ...
        item('ContourLevels', 20, 'numeric', 'Number of filled contour levels'), ...
        item('ColorLimits', [], 'numeric', 'Color limits [min max]'), ...
        item('XLim', [], 'numeric', 'Displayed X range [min max]'), ...
        item('YLim', [], 'numeric', 'Displayed Y range [min max]'), ...
        item('FontName', 'Times New Roman', 'text', 'Axes and label font', ...
            {'Times New Roman','Arial','Helvetica','Calibri'}), ...
        item('TextInterpreter', 'none', 'text', 'Title, label, and legend interpreter', ...
            {'none','tex','latex'}), ...
        item('FontSize', 11, 'numeric', 'Axes tick and label font size'), ...
        item('TitleFontSize', 12, 'numeric', 'Title font size'), ...
        item('TitleWeight', 'normal', 'text', 'Title font weight', {'normal','bold'}), ...
        item('AxisLineWidth', 1.0, 'numeric', 'Axes border and tick line width'), ...
        item('LineWidth', 1.8, 'numeric', 'Curve line width'), ...
        item('LineStyle', '-', 'text', 'Curve line style', {'-','--',':','-.'}), ...
        item('MarkerSymbol', 'none', 'text', 'Curve marker symbol', ...
            {'none','o','s','^','v','d','+','x','.'}), ...
        item('MarkerSize', 6, 'numeric', 'Curve marker size; scatter area uses its square'), ...
        item('ShowGrid', false, 'logical', 'Show major grid'), ...
        item('ShowMinorGrid', false, 'logical', 'Show minor grid'), ...
        item('GridLineStyle', ':', 'text', 'Grid line style', {'-',':','--','-.'}), ...
        item('GridAlpha', 0.18, 'numeric', 'Grid opacity from 0 to 1'), ...
        item('ShowColorbar', true, 'logical', 'Show colorbar for colored plots'), ...
        item('ShowLegend', true, 'logical', 'Show legend when named series exist'), ...
        item('LegendLocation', 'best', 'text', 'Legend placement', ...
            {'best','northeast','northwest','southeast','southwest', ...
             'northoutside','southoutside','eastoutside'}), ...
        item('LegendBox', false, 'logical', 'Draw legend border'), ...
        item('AxisEqual', false, 'logical', 'Use equal X/Y scale'), ...
        item('BoxOn', true, 'logical', 'Draw axes box'), ...
        item('TickDirection', 'out', 'text', 'Tick direction', {'out','in','both'}), ...
        item('ReverseX', false, 'logical', 'Reverse X direction'), ...
        item('ReverseY', false, 'logical', 'Reverse Y direction'), ...
        item('LogX', false, 'logical', 'Use logarithmic X axis'), ...
        item('LogY', false, 'logical', 'Use logarithmic Y axis'), ...
        item('Title', '', 'text', 'Override automatic title; empty keeps automatic'), ...
        item('XLabel', '', 'text', 'Override X label; empty keeps automatic'), ...
        item('YLabel', '', 'text', 'Override Y label; empty keeps automatic')];
    catalog(end + 1) = item('ColorbarLabel', '', 'text', ...
        'Override colorbar label; empty keeps the current label');
end

function value = item(name, defaultValue, typeName, description, allowedValues)
    if nargin < 5, allowedValues = {}; end
    value = struct('Name', name, 'Default', defaultValue, 'Type', typeName, ...
        'Target', 'plot', 'Description', description, ...
        'AllowedValues', {allowedValues});
end
