% run_selftest.m
baseDir = pwd;
outputLog = fullfile(baseDir, 'selftest_output.txt');
if exist(outputLog, 'file')
    delete(outputLog);
end
logFid = fopen(outputLog, 'w');
if logFid < 0
    error('selftest:LogOpenFail', 'Cannot open selftest_output.txt');
end

oldFigureVisible = get(0, 'DefaultFigureVisible');
set(0,'DefaultFigureVisible','off');
figureVisibleCleanup = onCleanup(@() restoreFigureVisible(oldFigureVisible)); %#ok<NASGU>
addpath(fileparts(baseDir));

fprintf('BASE|%s\n', baseDir); fprintf(logFid, 'BASE|%s\n', baseDir);

slurmPath = get_slurm_txt_fullpath(baseDir);
fprintf('SLURM|%s\n', slurmPath); fprintf(logFid, 'SLURM|%s\n', slurmPath);

expectError(@() run_analysis('cluster', 'BaseDir', baseDir, 'ClusterFile', 'cluster_chunk_test', ...
    'ClusterOptions', {'MakePlots', false, 'Dx', 0.5, 'Dim', 2}), ...
    'run_analysis:MissingTxtSuffix');
expectError(@() run_analysis('vx', 'BaseDir', baseDir, 'VxFile', 'vx_chunk_test', ...
    'VxOptions', {'MakePlot', false}), ...
    'run_analysis:MissingTxtSuffix');
expectError(@() run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'ChunkFile', 'bin2d_dx_0.5_dy_0.5_Lz_1', 'Variable', 'c_rho', 'DoPlot', false), ...
    'run_analysis:MissingTxtSuffix');
fprintf('EXPECT_BAD_SUFFIX|cluster=1|vx=1|chunk=1\n');
fprintf(logFid, 'EXPECT_BAD_SUFFIX|cluster=1|vx=1|chunk=1\n');

chunkPath = fullfile(baseDir, 'bin2d_dx_0.5_dy_0.5_Lz_1.txt');
progressTempDir = tempname;
mkdir(progressTempDir);
progressCleanup = onCleanup(@() cleanupTempDir(progressTempDir)); %#ok<NASGU>
progressChunkPath = fullfile(progressTempDir, 'progress_chunk_test.txt');
copyOk = copyfile(chunkPath, progressChunkPath);
assertTrue(copyOk == 1, 'Failed to prepare temp chunk file for progress tests.');

progressText1 = evalc('read_chunk_step_fast(progressChunkPath, ''Index'', 1, ''ProgressMode'', ''console'');');
assertContainsText(progressText1, 'Building index', ...
    'First indexed read should print building-index progress.');
assertContainsText(progressText1, '100%', ...
    'First indexed read should report 100%% completion.');
progressText2 = evalc('read_chunk_step_fast(progressChunkPath, ''Index'', 1, ''ProgressMode'', ''console'');');
assertTrue(isempty(strtrim(progressText2)), ...
    'Cached read_chunk_step_fast call should not print progress.');
progressText3 = evalc('read_bin_chunk(progressChunkPath, ''ProgressMode'', ''console'');');
assertContainsText(progressText3, 'Reading file', ...
    'read_bin_chunk should print reading progress.');
assertContainsText(progressText3, '100%', ...
    'read_bin_chunk should report 100%% completion.');
progressText4 = evalc('read_bin_chunk(progressChunkPath, ''ProgressMode'', ''console'');');
assertContainsText(progressText4, 'Reading file', ...
    'Repeated read_bin_chunk call should still print progress.');
progressTextAuto = evalc('read_bin_chunk(progressChunkPath, ''ProgressMode'', ''auto'');');
if usejava('desktop') && usejava('awt')
    assertTrue(isempty(strtrim(progressTextAuto)) || ~isempty(strfind(progressTextAuto, 'Reading file')), ...
        'ProgressMode=auto should use waitbar or console output on desktop MATLAB.');
else
    assertContainsText(progressTextAuto, 'Reading file', ...
        'ProgressMode=auto should fall back to console output in batch mode.');
end
progressTextOff = evalc('read_bin_chunk(progressChunkPath, ''ProgressMode'', ''off'');');
assertTrue(isempty(strtrim(progressTextOff)), ...
    'read_bin_chunk with ProgressMode=off should not print progress.');
runOffText = evalc(['run_analysis(''chunk'', ''BaseDir'', baseDir, ''ChunkDim'', ''2d'', ' ...
    '''ChunkFile'', ''bin2d_dx_0.5_dy_0.5_Lz_1.txt'', ''Variable'', ''c_rho'', ' ...
    '''Index'', 1, ''ProgressMode'', ''off'', ''DoPlot'', false);']);
assertTrue(isempty(strtrim(runOffText)), ...
    'run_analysis with ProgressMode=off should not print progress.');
fprintf('PROGRESS_TESTS_OK\n');
fprintf(logFid, 'PROGRESS_TESTS_OK\n');

step = read_chunk_step_fast(chunkPath, 'SelectBy', 'Time', 'Time', 10, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off');
idxRho = step.colIndex.c_rho;
idxMass = step.colIndex.v_mass;
rhoSum = sum(step.data(isfinite(step.data(:,idxRho)), idxRho));
fprintf('CHUNK_STEP|timestep=%g|stepIndex=%d|rows=%d\n', step.timestep, step.stepIndex, size(step.data,1));
fprintf(logFid, 'CHUNK_STEP|timestep=%g|stepIndex=%d|rows=%d\n', step.timestep, step.stepIndex, size(step.data,1));
fprintf('CHUNK_RHO_SUM|%.6f\n', rhoSum); fprintf(logFid, 'CHUNK_RHO_SUM|%.6f\n', rhoSum);
fprintf('CHUNK_ROW3_MASS_ISNAN|%d\n', isnan(step.data(3, idxMass))); fprintf(logFid, 'CHUNK_ROW3_MASS_ISNAN|%d\n', isnan(step.data(3, idxMass)));

stepExplicitIndex = read_chunk_step_fast(chunkPath, ...
    'SelectBy', 'Index', 'Index', 1, 'Time', 999, 'TimeStep', 999, ...
    'ProgressMode', 'off');
assertTrue(stepExplicitIndex.stepIndex == 1 && stepExplicitIndex.timestep == 100, ...
    'Explicit SelectBy=Index must take precedence over non-empty Time/TimeStep values.');

outChunkRaw = run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'Variable', 'c_rho', 'SelectBy', 'Time', 'Time', 20, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off', 'DoPlot', false);
fprintf('RUN_CHUNK_RAW|timestep=%g|n=%d\n', outChunkRaw.timestep, numel(outChunkRaw.value));
fprintf(logFid, 'RUN_CHUNK_RAW|timestep=%g|n=%d\n', outChunkRaw.timestep, numel(outChunkRaw.value));

dV = 0.5 * 0.5 * 1.0;
outChunkVM = run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'Variable', 'vonMisesS', 'SelectBy', 'TimeStep', 'TimeStep', 200, ...
    'dV', dV, 'ProgressMode', 'off', 'DoPlot', false);
vm = outChunkVM.value;
vmFin = vm(isfinite(vm));
fprintf('RUN_CHUNK_VM|timestep=%g|min=%.6f|max=%.6f\n', outChunkVM.timestep, min(vmFin), max(vmFin));
fprintf(logFid, 'RUN_CHUNK_VM|timestep=%g|min=%.6f|max=%.6f\n', outChunkVM.timestep, min(vmFin), max(vmFin));

refChunk = compute_temp_stress_chunk(chunkPath, 'SelectBy', 'Time', 'Time', 10, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off', 'dV', dV);
expectedDensity = step.data(:, idxMass) ./ dV .* 1.66053906660;
outChunkVelocity = run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'ChunkFile', 'bin2d_dx_0.5_dy_0.5_Lz_1.txt', ...
    'Variable', 'velocity', 'SelectBy', 'Time', 'Time', 10, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off', 'DoPlot', false);
outChunkPressure = run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'ChunkFile', 'bin2d_dx_0.5_dy_0.5_Lz_1.txt', ...
    'Variable', 'pressure', 'SelectBy', 'Time', 'Time', 10, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off', 'dV', dV, 'DoPlot', false);
outChunkDensity = run_analysis('chunk', 'BaseDir', baseDir, 'ChunkDim', '2d', ...
    'ChunkFile', 'bin2d_dx_0.5_dy_0.5_Lz_1.txt', ...
    'Variable', 'density', 'SelectBy', 'Time', 'Time', 10, ...
    'SlurmPath', slurmPath, 'ProgressMode', 'off', 'dV', dV, 'DoPlot', false);
assertArrayApprox(outChunkVelocity.value, refChunk.speed, 1e-12, ...
    'Derived velocity should match compute_temp_stress_chunk speed.');
assertArrayApprox(outChunkPressure.value, refChunk.pressure, 1e-12, ...
    'Derived pressure should match compute_temp_stress_chunk pressure.');
assertArrayApprox(refChunk.density, expectedDensity, 1e-12, ...
    'compute_temp_stress_chunk density should divide every bin by the scalar dV.');
assertArrayApprox(outChunkDensity.value, expectedDensity, 1e-12, ...
    'Derived density should match the manual mass/volume conversion.');
assertTrue(sum(isfinite(outChunkDensity.value)) == sum(isfinite(expectedDensity)), ...
    'Density should stay finite for every non-empty bin when dV is scalar.');
fprintf('RUN_CHUNK_DERIVED|velocityMax=%.6f|pressureMean=%.6f|densityMean=%.6f\n', ...
    max(outChunkVelocity.value(isfinite(outChunkVelocity.value))), ...
    mean(outChunkPressure.value(isfinite(outChunkPressure.value))), ...
    mean(outChunkDensity.value(isfinite(outChunkDensity.value))));
fprintf(logFid, 'RUN_CHUNK_DERIVED|velocityMax=%.6f|pressureMean=%.6f|densityMean=%.6f\n', ...
    max(outChunkVelocity.value(isfinite(outChunkVelocity.value))), ...
    mean(outChunkPressure.value(isfinite(outChunkPressure.value))), ...
    mean(outChunkDensity.value(isfinite(outChunkDensity.value))));

outCluster = run_analysis('cluster', 'BaseDir', baseDir, 'ClusterFile', 'cluster_chunk_test.txt', ...
    'SelectBy', 'Time', 'Time', 10, 'SlurmPath', slurmPath, ...
    'ProgressMode', 'off', ...
    'ClusterOptions', {'MakePlots', false, 'Dx', 0.5, 'Dim', 2});
outClusterScaled = run_analysis('cluster', 'BaseDir', baseDir, 'ClusterFile', 'cluster_chunk_test.txt', ...
    'SelectBy', 'Time', 'Time', 10, 'SlurmPath', slurmPath, ...
    'ProgressMode', 'off', 'CoordScale', 7, ...
    'ClusterOptions', {'MakePlots', false, 'Dx', 0.5, 'Dim', 2});
assertApprox(outCluster.stats.mean, mean(outCluster.diameter), 1e-12, ...
    'Default cluster mean should remain arithmetic mean.');
assertArrayApprox(outClusterScaled.diameter, outCluster.diameter, 1e-12, ...
    'Top-level CoordScale must not affect cluster results.');
fprintf('RUN_CLUSTER|timestep=%g|selectedRows=%d|diameterMean=%.6f\n', ...
    outCluster.timestep, outCluster.selectedRows, outCluster.stats.mean);
fprintf(logFid, 'RUN_CLUSTER|timestep=%g|selectedRows=%d|diameterMean=%.6f\n', ...
    outCluster.timestep, outCluster.selectedRows, outCluster.stats.mean);

rangeDia = [0.95 1.35];
outClusterFiltered = run_analysis('cluster', 'BaseDir', baseDir, ...
    'ClusterFile', 'cluster_chunk_test.txt', ...
    'SelectBy', 'Time', 'Time', 10, 'SlurmPath', slurmPath, ...
    'ProgressMode', 'off', ...
    'ClusterOptions', {'MakePlots', true, 'Dx', 0.5, 'Dim', 2, ...
                       'Range_diameter', rangeDia, ...
                       'MeanPowerM', 2, 'MeanPowerN', 1, ...
                       'MeanNumBins', 2, 'HistNumBins', 4});
expectedSelected = sum(outCluster.diameter >= rangeDia(1) & outCluster.diameter <= rangeDia(2));
assertTrue(outClusterFiltered.selectedRows == expectedSelected, ...
    'Range_diameter should reduce selected rows consistently.');
expectedCustomMean = sum(outClusterFiltered.diameter .^ 2) / sum(outClusterFiltered.diameter);
assertApprox(outClusterFiltered.stats.mean, expectedCustomMean, 1e-12, ...
    'Custom cluster mean should use sum(d^m)/sum(d^n).');
assertTrue(outClusterFiltered.meanDefinition.m == 2 && outClusterFiltered.meanDefinition.n == 1, ...
    'meanDefinition should record the configured powers.');

xVals = outClusterFiltered.filteredData(:, outClusterFiltered.colIndex.c_x);
expectedBinMeans = computeBinnedMomentMeans(xVals, outClusterFiltered.diameter, ...
    outClusterFiltered.meanByBin.edges, 2, 1);
validBins = ~isnan(expectedBinMeans);
assertApprox(max(abs(outClusterFiltered.meanByBin.meanDiameter(validBins) - expectedBinMeans(validBins))), ...
    0, 1e-12, 'Binned diameter mean should use the same power-ratio definition.');

assertTrue(ishandle(outClusterFiltered.plots.countFig), 'countFig should be returned when MakePlots=true.');
assertTrue(ishandle(outClusterFiltered.plots.probFig), 'probFig should be returned when MakePlots=true.');
assertTrue(ishandle(outClusterFiltered.plots.cdfFig), 'cdfFig should be returned when MakePlots=true.');
assertTrue(ishandle(outClusterFiltered.plots.meanFig), 'meanFig should be returned when MakePlots=true.');
assertTrue(outClusterFiltered.plots.histFig == outClusterFiltered.plots.countFig, ...
    'histFig should remain as a compatibility alias of countFig.');
fprintf('RUN_CLUSTER_FILTERED|timestep=%g|selectedRows=%d|diameterMean=%.6f\n', ...
    outClusterFiltered.timestep, outClusterFiltered.selectedRows, outClusterFiltered.stats.mean);
fprintf(logFid, 'RUN_CLUSTER_FILTERED|timestep=%g|selectedRows=%d|diameterMean=%.6f\n', ...
    outClusterFiltered.timestep, outClusterFiltered.selectedRows, outClusterFiltered.stats.mean);
fprintf('RUN_CLUSTER_PLOTS|countFig=%d|probFig=%d|histAlias=%d\n', ...
    ishandle(outClusterFiltered.plots.countFig), ...
    ishandle(outClusterFiltered.plots.probFig), ...
    outClusterFiltered.plots.histFig == outClusterFiltered.plots.countFig);
fprintf(logFid, 'RUN_CLUSTER_PLOTS|countFig=%d|probFig=%d|histAlias=%d\n', ...
    ishandle(outClusterFiltered.plots.countFig), ...
    ishandle(outClusterFiltered.plots.probFig), ...
    outClusterFiltered.plots.histFig == outClusterFiltered.plots.countFig);
close([outClusterFiltered.plots.countFig, outClusterFiltered.plots.probFig, ...
       outClusterFiltered.plots.cdfFig, outClusterFiltered.plots.meanFig]);

clusterDiameterPlotRange = [0.9 1.4];
outClusterHistBins = run_analysis('cluster', 'BaseDir', baseDir, ...
    'ClusterFile', 'cluster_chunk_test.txt', ...
    'SelectBy', 'Time', 'Time', 10, 'SlurmPath', slurmPath, ...
    'ProgressMode', 'off', ...
    'ClusterOptions', {'MakePlots', true, 'Dx', 0.5, 'Dim', 2, ...
                       'DiameterHistBinSize', 0.1, ...
                       'DiameterPlotRange', clusterDiameterPlotRange});
assertApprox(max(abs(diff(outClusterHistBins.hist.edges) - 0.1)), 0, 1e-12, ...
    'Cluster DiameterHistBinSize should control histogram edge spacing.');
clusterCountAxes = getFigureDataAxes(outClusterHistBins.plots.countFig);
assertArrayApprox(get(clusterCountAxes(1), 'XLim'), clusterDiameterPlotRange, 1e-12, ...
    'Cluster DiameterPlotRange should crop count distribution x limits.');
clusterProbAxes = getFigureDataAxes(outClusterHistBins.plots.probFig);
assertArrayApprox(get(clusterProbAxes(1), 'XLim'), clusterDiameterPlotRange, 1e-12, ...
    'Cluster DiameterPlotRange should crop probability distribution x limits.');
clusterCdfAxes = getFigureDataAxes(outClusterHistBins.plots.cdfFig);
assertArrayApprox(get(clusterCdfAxes(1), 'XLim'), clusterDiameterPlotRange, 1e-12, ...
    'Cluster DiameterPlotRange should crop CDF x limits.');
closeHandles(collectPlotHandles(outClusterHistBins.plots));

outVx = run_analysis('vx', 'BaseDir', baseDir, 'VxFile', 'vx_chunk_test.txt', ...
    'SelectBy', 'Time', 'Time', 20, 'SlurmPath', slurmPath, ...
    'ProgressMode', 'off', ...
    'VxOptions', {'MakePlot', false, 'VelocityFactor', 0.001});
fprintf('RUN_VX|timestep=%g|nVelocity=%d|nPlotted=%d\n', ...
    outVx.timestep, numel(outVx.velocity), numel(outVx.plottedVars));
fprintf(logFid, 'RUN_VX|timestep=%g|nVelocity=%d|nPlotted=%d\n', ...
    outVx.timestep, numel(outVx.velocity), numel(outVx.plottedVars));
if ~isempty(outVx.plottedVars)
    fprintf('RUN_VX_PLOTTED|%s\n', strjoin(outVx.plottedVars, ','));
    fprintf(logFid, 'RUN_VX_PLOTTED|%s\n', strjoin(outVx.plottedVars, ','));
else
    fprintf('RUN_VX_PLOTTED|<none>\n');
    fprintf(logFid, 'RUN_VX_PLOTTED|<none>\n');
end

networkTempDir = tempname;
mkdir(networkTempDir);
networkCleanup = onCleanup(@() cleanupTempDir(networkTempDir)); %#ok<NASGU>
ringPath = fullfile(networkTempDir, 'bin2d_case_ring_dx_1_dy_1.txt');
diagPath = fullfile(networkTempDir, 'bin2d_case_diag_dx_1_dy_1.txt');
wrapMergeXPath = fullfile(networkTempDir, 'bin2d_case_wrapx_merge_dx_1_dy_1.txt');
wrapMergeYPath = fullfile(networkTempDir, 'bin2d_case_wrapy_merge_dx_1_dy_1.txt');
wrapTrueXPath = fullfile(networkTempDir, 'bin2d_case_wrapx_true_dx_1_dy_1.txt');
wrapTrueYPath = fullfile(networkTempDir, 'bin2d_case_wrapy_true_dx_1_dy_1.txt');
torusFullPath = fullfile(networkTempDir, 'bin2d_case_torus_full_dx_1_dy_1.txt');
allMatrixPath = fullfile(networkTempDir, 'bin2d_case_all_matrix_dx_1_dy_1.txt');
profileCenterPath = fullfile(networkTempDir, 'bin2d_case_profile_center_dx_1_dy_1.txt');
sizeStatsPath = fullfile(networkTempDir, 'bin2d_case_size_stats_dx_1_dy_1.txt');
labelRankPath = fullfile(networkTempDir, 'bin2d_case_label_rank_dx_1_dy_1.txt');
branchPath = fullfile(networkTempDir, 'bin2d_case_branch_dx_1_dy_1.txt');
neckPath = fullfile(networkTempDir, 'bin2d_case_neck_dx_1_dy_1.txt');
fragmentPath = fullfile(networkTempDir, 'bin2d_case_fragment_dx_1_dy_1.txt');
evolutionPath = fullfile(networkTempDir, 'bin2d_case_evolution_dx_1_dy_1.txt');
line1dPath = fullfile(networkTempDir, 'bin1d_case_line_dx_1.txt');

writeChunk2dCase(ringPath, [2 2 2; 2 0 2; 2 2 2], 100);
writeChunk2dCase(diagPath, [0 2; 2 0], 100);
writeChunk2dCase(wrapMergeXPath, [0 2 0], 100);
writeChunk2dCase(wrapMergeYPath, [0; 2; 0], 100);
writeChunk2dCase(wrapTrueXPath, [0 0 0], 100);
writeChunk2dCase(wrapTrueYPath, [0; 0; 0], 100);
writeChunk2dCase(torusFullPath, zeros(3, 3), 100);
writeChunk2dCase(allMatrixPath, 2 * ones(2, 2), 100);
writeChunk2dCase(profileCenterPath, [0 0 2; 0 0 2; 0 0 2], 100);
writeChunk2dCase(sizeStatsPath, [0 0 2 2; 2 2 2 2; 2 2 2 0], 100);
writeChunk2dCase(labelRankPath, [0 2 2; 2 2 2; 2 0 0], 100);
writeChunk2dCase(branchPath, [2 2 0 2 2; 2 2 0 2 2; 0 0 0 0 0; 2 2 0 2 2; 2 2 0 2 2], 100);
writeChunk2dCase(neckPath, [2 2 2 0 2 2 2; 2 2 2 0 2 2 2; 2 2 2 2 2 2 2; 2 2 2 0 2 2 2; 2 2 2 0 2 2 2], 100);
writeChunk2dCase(fragmentPath, [2 0 2; 0 0 0; 2 0 2], 100);
writeChunk2dStepsCase(evolutionPath, ...
    {[0 2 0; 2 2 2; 2 2 2], ...
     [0 0 0; 2 2 2; 2 2 2], ...
     [0 0 0; 0 2 0; 0 0 0], ...
     [0 2 0; 0 0 0; 0 2 0]}, ...
    [100 200 300 400]);
writeChunk1dCase(line1dPath, [0 1 2], 100);

outChunk1dRange = run_analysis('chunk', 'BaseDir', networkTempDir, 'ChunkDim', '1d', ...
    'ChunkFile', 'bin1d_case_line_dx_1.txt', 'Variable', 'Ncount', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'CoordScale', 2, 'CoordRangeX', [1 4.5], 'DoPlot', false);
assertArrayApprox(outChunk1dRange.x, [2; 4], 1e-12, ...
    '1D chunk coordinates should be scaled and filtered by CoordRangeX.');
assertArrayApprox(outChunk1dRange.value, [1; 2], 1e-12, ...
    '1D chunk values should stay aligned after coordinate filtering.');

outChunk2dRange = run_analysis('chunk', 'BaseDir', networkTempDir, 'ChunkDim', '2d', ...
    'ChunkFile', 'bin2d_case_ring_dx_1_dy_1.txt', 'Variable', 'Ncount', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'CoordScale', 2, 'CoordRangeX', [1 3], 'CoordRangeY', [1 5], 'DoPlot', false);
assertArrayApprox(outChunk2dRange.x, [2; 2], 1e-12, ...
    '2D chunk x coordinates should be scaled and filtered by CoordRangeX.');
assertArrayApprox(outChunk2dRange.y, [2; 4], 1e-12, ...
    '2D chunk y coordinates should be scaled and filtered by CoordRangeY.');
assertArrayApprox(outChunk2dRange.value, [0; 2], 1e-12, ...
    '2D chunk values should stay aligned after coordinate filtering.');

expectError(@() run_analysis('network2d', 'BaseDir', networkTempDir, ...
    'ChunkFile', 'bin2d_case_ring_dx_1_dy_1.txt', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off'), ...
    'analyze_chunk_network2d:MissingThresholdN');
expectError(@() run_analysis('network2d', 'BaseDir', networkTempDir, ...
    'ChunkFile', 'bin1d_case_line_dx_1.txt', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'NetworkOptions', {'ThresholdN', 1, 'MakePlots', false}), ...
    'analyze_chunk_network2d:Not2DChunk');

outNetwork = run_analysis('network2d', 'BaseDir', networkTempDir, ...
    'ChunkFile', 'bin2d_case_ring_dx_1_dy_1.txt', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'NetworkOptions', {'ThresholdN', 1, 'MakePlots', false, ...
                       'PositionAxis', 'both', 'ProfileAxis', 'x', 'ProfileNumBins', 1});
assertApprox(outNetwork.global.porosity, 1/9, 1e-12, ...
    'Porosity should equal pore area fraction.');
assertApprox(outNetwork.global.interfaceLength, 4, 1e-12, ...
    'Interface length should equal the central-cell perimeter in the ring case.');
assertApprox(outNetwork.global.specificInterfaceBulk, 4/9, 1e-12, ...
    'Bulk specific interface should divide interface length by total valid area.');
assertTrue(outNetwork.pore.numComponents == 1, ...
    'Ring case should contain one pore component.');
assertTrue(outNetwork.matrix.numComponents == 1, ...
    'Ring case should contain one matrix component.');
assertTrue(outNetwork.matrix.holeCount == 1, ...
    'Ring matrix should contain one enclosed hole.');
assertTrue(outNetwork.pore.holeCount == 0, ...
    'Single-cell pore should not contain holes.');
assertTrue(outNetwork.matrix.percolatesX == 1 && outNetwork.matrix.percolatesY == 1, ...
    'Ring matrix should percolate in both directions under open boundaries.');
assertTrue(outNetwork.pore.percolatesX == 0 && outNetwork.pore.percolatesY == 0, ...
    'Central pore should not percolate under open boundaries.');
assertTrue(outNetwork.pore.connectivity.x.isConnected == 0 && outNetwork.pore.connectivity.y.isConnected == 0, ...
    'Direct pore connectivity flags should report no x/y connection for the central pore.');
assertTrue(outNetwork.matrix.connectivity.x.isConnected == 1 && outNetwork.matrix.connectivity.y.isConnected == 1, ...
    'Direct matrix connectivity flags should report x/y connection for the ring matrix.');
assertApprox(outNetwork.profile.x.porosity(1), outNetwork.global.porosity, 1e-12, ...
    'Single-bin x profile porosity should match the global porosity.');
assertApprox(outNetwork.profile.x.specificInterfaceBulk(1), outNetwork.global.specificInterfaceBulk, 1e-12, ...
    'Single-bin x profile specific interface should match the global value.');
assertTrue(outNetwork.profile.x.connectivityFlag(1) == 0, ...
    'Single-bin x profile should report no perpendicular pore connection for the central pore.');
assertApprox(outNetwork.profile.x.connectivityFraction(1), 0, 1e-12, ...
    'Single-bin x profile connectivity fraction should be zero for the central pore.');
assertTrue(outNetwork.poreMask(2, 2) == 1 && sum(outNetwork.poreMask(:)) == 1, ...
    'Threshold-based classification should mark only the center cell as pore.');
expectedPoreDiameter = 2 * sqrt(1 / pi);
assertApprox(outNetwork.pore.components.equivDiameter(1), expectedPoreDiameter, 1e-12, ...
    'Single-cell equivalent diameter should match the analytical 2D definition.');
assertTrue(sum(outNetwork.pore.positionDistribution.x.count) == 1, ...
    'Position distribution should contain the single pore component.');
assertTrue(outNetwork.stats.topology.pore.beta0 == 1 && outNetwork.stats.topology.pore.beta1 == 0 && outNetwork.stats.topology.pore.chi == 1, ...
    'Pore Betti numbers should match the single-cell pore topology.');
assertTrue(outNetwork.stats.topology.matrix.beta0 == 1 && outNetwork.stats.topology.matrix.beta1 == 1 && outNetwork.stats.topology.matrix.chi == 0, ...
    'Matrix Betti numbers should match the ring topology.');
assertApprox(outNetwork.stats.connectivity.pore.largestFraction, 1, 1e-12, ...
    'Single pore component should occupy the full pore phase.');
assertTrue(outNetwork.stats.connectivity.matrix.percolatesX == 1 && outNetwork.stats.connectivity.matrix.percolatesY == 1, ...
    'Matrix percolation flags in stats should match the ring case.');
assertApprox(outNetwork.stats.geometry.phi, outNetwork.global.porosity, 1e-12, ...
    'stats.geometry.phi should match the global porosity.');
assertApprox(outNetwork.stats.geometry.interfaceLength, outNetwork.global.interfaceLength, 1e-12, ...
    'stats.geometry.interfaceLength should match the legacy global field.');
assertApprox(outNetwork.stats.geometry.specificInterface, outNetwork.global.specificInterfaceBulk, 1e-12, ...
    'stats.geometry.specificInterface should match the legacy bulk specific interface.');
assertTrue(~isfield(outNetwork.stats.size.pore, 'area'), ...
    'stats.size should not expose area vectors when size statistics use diameter only.');
assertTrue(~isfield(outNetwork.stats.size.pore, 'radius'), ...
    'stats.size should not expose radius vectors when size statistics use diameter only.');
assertApprox(outNetwork.stats.size.pore.meanDiameter, expectedPoreDiameter, 1e-12, ...
    'Mean diameter should default to the arithmetic mean when MeanPowerM/N are 1/0.');
assertTrue(outNetwork.stats.fragmentation.matrix.count == 1, ...
    'Single matrix ring should not be fragmented.');

outDiag = analyze_chunk_network2d(diagPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false);
assertTrue(outDiag.pore.numComponents == 2, ...
    'Diagonal pore cells must stay disconnected under 4-neighbor connectivity.');

outWrapXOpen = analyze_chunk_network2d(wrapMergeXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'open', 'MakePlots', false);
assertTrue(outWrapXOpen.pore.numComponents == 2, ...
    'Left/right edge pores should remain disconnected without periodic boundaries.');
outWrapXMerge = analyze_chunk_network2d(wrapMergeXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-x', 'MakePlots', false);
assertTrue(outWrapXMerge.pore.numComponents == 1 && outWrapXMerge.pore.wrapsX == 0, ...
    'Periodic-x should merge opposite-edge pores without claiming x wrap when no winding exists.');
assertTrue(outWrapXMerge.pore.connectivity.x.isConnected == 0, ...
    'Direct x-connectivity should stay false when the merged pore component has no winding.');
assertTrue(outWrapXMerge.pore.holeCount == 0 && outWrapXMerge.pore.eulerCharacteristic == 1, ...
    'Periodic-x merged pores without winding should still have beta1=0 and chi=1.');
assertTrue(outWrapXMerge.stats.topology.pore.beta0 == 1 && ...
           outWrapXMerge.stats.topology.pore.beta1 == 0 && ...
           outWrapXMerge.stats.topology.pore.chi == 1, ...
    'Wrapped periodic-x topology should report the correct non-winding Betti numbers.');

outWrapYMerge = analyze_chunk_network2d(wrapMergeYPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-y', 'MakePlots', false);
assertTrue(outWrapYMerge.pore.numComponents == 1 && outWrapYMerge.pore.wrapsY == 0, ...
    'Periodic-y should merge opposite-edge pores without claiming y wrap when no winding exists.');

outWrapXTrue = analyze_chunk_network2d(wrapTrueXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-x', 'MakePlots', false);
assertTrue(outWrapXTrue.pore.numComponents == 1 && outWrapXTrue.pore.wrapsX == 1, ...
    'A fully occupied periodic-x pore row should be detected as true x wrap.');
assertTrue(outWrapXTrue.pore.connectivity.x.isConnected == 1, ...
    'True periodic winding should report x connectivity.');
assertTrue(outWrapXTrue.stats.topology.pore.beta0 == 1 && ...
           outWrapXTrue.stats.topology.pore.beta1 == 1 && ...
           outWrapXTrue.stats.topology.pore.chi == 0, ...
    'A fully occupied periodic-x pore row should be a cylinder with beta1=1 and chi=0.');

outWrapYTrue = analyze_chunk_network2d(wrapTrueYPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-y', 'MakePlots', false);
assertTrue(outWrapYTrue.pore.numComponents == 1 && outWrapYTrue.pore.wrapsY == 1, ...
    'A fully occupied periodic-y pore column should be detected as true y wrap.');
assertTrue(outWrapYTrue.pore.connectivity.y.isConnected == 1, ...
    'True periodic winding should report y connectivity.');
assertTrue(outWrapYTrue.stats.topology.pore.beta0 == 1 && ...
           outWrapYTrue.stats.topology.pore.beta1 == 1 && ...
           outWrapYTrue.stats.topology.pore.chi == 0, ...
    'A fully occupied periodic-y pore column should be a cylinder with beta1=1 and chi=0.');

outTorusFull = analyze_chunk_network2d(torusFullPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-xy', 'MakePlots', false);
assertTrue(outTorusFull.pore.numComponents == 1 && outTorusFull.pore.wrapsX == 1 && outTorusFull.pore.wrapsY == 1, ...
    'A fully occupied periodic-xy pore field should wrap in both directions.');
assertTrue(outTorusFull.stats.topology.pore.beta0 == 1 && ...
           outTorusFull.stats.topology.pore.beta1 == 2 && ...
           outTorusFull.stats.topology.pore.chi == 0 && ...
           outTorusFull.stats.topology.pore.beta2 == 1, ...
    'A fully occupied periodic-xy pore field should recover the torus Betti numbers.');
assertApprox(outTorusFull.stats.connectivity.matrix.largestFraction, 0, 1e-12, ...
    'An empty matrix phase should report largestFraction=0 instead of NaN.');
assertApprox(outTorusFull.stats.connectivity.matrix.connectedAreaFractionX, 0, 1e-12, ...
    'An empty matrix phase should report connectedAreaFractionX=0 instead of NaN.');
assertApprox(outTorusFull.stats.fragmentation.matrix.largestFraction, 0, 1e-12, ...
    'Matrix fragmentation largestFraction should stay zero when the matrix phase is empty.');

outAllMatrix = analyze_chunk_network2d(allMatrixPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'open', 'MakePlots', false, ...
    'EnableSkeletonGraph', true);
assertTrue(outAllMatrix.stats.topology.pore.beta0 == 0 && outAllMatrix.stats.topology.pore.beta1 == 0, ...
    'An all-matrix case should keep the pore topology empty.');
assertApprox(outAllMatrix.stats.connectivity.pore.largestFraction, 0, 1e-12, ...
    'An empty pore phase should report largestFraction=0 instead of NaN.');
assertApprox(outAllMatrix.stats.connectivity.pore.connectedAreaFractionX, 0, 1e-12, ...
    'An empty pore phase should report connectedAreaFractionX=0 instead of NaN.');
assertTrue(outAllMatrix.stats.network.pore.branchDensity == 0, ...
    'Empty-phase skeleton branch density should be zero when skeleton analysis is enabled.');

outWrapXProfile = analyze_chunk_network2d(wrapMergeXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-x', 'MakePlots', false, ...
    'ProfileAxis', 'y', 'ProfileNumBins', 1);
assertTrue(outWrapXProfile.profile.y.connectivityFlag(1) == 0, ...
    'Single-bin y profile should stay disconnected when periodic merging creates no true x wrap.');
assertApprox(outWrapXProfile.profile.y.connectivityFraction(1), 0, 1e-12, ...
    'Single-bin y profile connectivity fraction should be zero without a wrapped component.');

outWrapTrueXProfile = analyze_chunk_network2d(wrapTrueXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'periodic-x', 'MakePlots', false, ...
    'ProfileAxis', 'y', 'ProfileNumBins', 1);
assertTrue(outWrapTrueXProfile.profile.y.connectivityFlag(1) == 1, ...
    'Single-bin y profile should detect true x-direction wrapped pores.');
assertApprox(outWrapTrueXProfile.profile.y.connectivityFraction(1), 1, 1e-12, ...
    'Single-bin y profile connectivity fraction should be one when the only pore component wraps.');

outNetworkScaled = run_analysis('network2d', 'BaseDir', networkTempDir, ...
    'ChunkFile', 'bin2d_case_ring_dx_1_dy_1.txt', ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'CoordScale', 2, ...
    'NetworkOptions', {'ThresholdN', 1, 'MakePlots', false});
assertArrayApprox(outNetworkScaled.xCenters(:), [0; 2; 4], 1e-12, ...
    'Network xCenters should scale with CoordScale.');
assertArrayApprox(outNetworkScaled.yCenters(:), [0; 2; 4], 1e-12, ...
    'Network yCenters should scale with CoordScale.');
assertApprox(outNetworkScaled.dx, 2, 1e-12, ...
    'Filename-derived dx should scale with CoordScale.');
assertApprox(outNetworkScaled.dy, 2, 1e-12, ...
    'Filename-derived dy should scale with CoordScale.');
assertApprox(outNetworkScaled.global.interfaceLength, 8, 1e-12, ...
    'Interface length should scale linearly with CoordScale.');
assertApprox(outNetworkScaled.global.specificInterfaceBulk, 2/9, 1e-12, ...
    'Bulk specific interface should scale inversely with CoordScale.');

outNetworkScaledOption = analyze_chunk_network2d(ringPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, ...
    'CoordScale', 3, 'Dx', 1, 'Dy', 1);
assertApprox(outNetworkScaledOption.dx, 3, 1e-12, ...
    'Explicit Dx should still scale with CoordScale.');
assertApprox(outNetworkScaledOption.dy, 3, 1e-12, ...
    'Explicit Dy should still scale with CoordScale.');

outPositionRange = analyze_chunk_network2d(wrapMergeXPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'open', 'MakePlots', false, ...
    'PositionAxis', 'x', 'PositionNumBins', 2, 'PositionRangeX', [1.5 2.5]);
assertTrue(sum(outPositionRange.pore.positionDistribution.x.count) == 1, ...
    'PositionRangeX should keep only pore components whose centroids fall in range.');
assertTrue(outPositionRange.pore.numComponents == 2, ...
    'PositionRangeX must not change global connected-component counts.');

outProfileRange = analyze_chunk_network2d(ringPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, ...
    'ProfileAxis', 'x', 'ProfileNumBins', 1, 'ProfileRangeX', [0.5 1.5]);
assertApprox(outProfileRange.profile.x.range(1), 0.5, 1e-12, ...
    'ProfileRangeX should define the lower profile edge.');
assertApprox(outProfileRange.profile.x.range(2), 1.5, 1e-12, ...
    'ProfileRangeX should define the upper profile edge.');
assertApprox(outProfileRange.profile.x.porosity(1), 1/3, 1e-12, ...
    'ProfileRangeX should restrict local porosity to the requested slice range.');
assertApprox(outProfileRange.global.porosity, 1/9, 1e-12, ...
    'ProfileRangeX must not change global porosity.');

outCenterProfile = analyze_chunk_network2d(profileCenterPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'Boundary', 'open', 'MakePlots', false, ...
    'ProfileAxis', 'x', 'ProfileNumBins', 3);
assertArrayApprox(outCenterProfile.profile.x.connectivityFlag(:), [0; 1; 0], 1e-12, ...
    'Profile connectivity should be assigned only to the bin containing the connected component centroid.');
assertArrayApprox(outCenterProfile.profile.x.connectivityComponentCount(:), [0; 1; 0], 1e-12, ...
    'Only the centroid bin should count the vertically connected pore component.');
assertArrayApprox(outCenterProfile.profile.x.connectivityArea(:), [0; 6; 0], 1e-12, ...
    'Connected component area should be accumulated only in the centroid bin.');
assertArrayApprox(outCenterProfile.profile.x.componentPoreArea(:), [0; 6; 0], 1e-12, ...
    'componentPoreArea should follow centroid-based component assignment.');
assertArrayApprox(outCenterProfile.profile.x.connectivityFraction(:), [0; 1; 0], 1e-12, ...
    'connectivityFraction should divide connected area by centroid-assigned component area.');

outSizeStats = analyze_chunk_network2d(sizeStatsPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, 'MeanPowerM', 2, 'MeanPowerN', 1);
expectedSizeDiameters = sort([2 * sqrt(2 / pi); 2 * sqrt(1 / pi)]);
assertArrayApprox(sort(outSizeStats.stats.size.pore.diameter), expectedSizeDiameters, 1e-12, ...
    'Size stats should report every pore-component diameter.');
expectedMomentMean = sum(expectedSizeDiameters .^ 2) / sum(expectedSizeDiameters);
assertApprox(outSizeStats.stats.size.pore.meanDiameter, expectedMomentMean, 1e-12, ...
    'MeanPowerM/N should control the pore mean diameter definition.');
expectedAreaWeighted = (2 * expectedSizeDiameters(2) + 1 * expectedSizeDiameters(1)) / 3;
assertApprox(outSizeStats.stats.size.pore.areaWeightedMeanDiameter, expectedAreaWeighted, 1e-12, ...
    'Area-weighted mean diameter should remain a separate fixed statistic.');
assertTrue(~isfield(outSizeStats.stats.size.pore, 'meanArea'), ...
    'stats.size should not expose area means when size statistics use diameter only.');
assertTrue(~isfield(outSizeStats.stats.size.pore, 'meanRadius'), ...
    'stats.size should not expose radius means when size statistics use diameter only.');
assertTrue(~isfield(outSizeStats.stats.size.pore.hist, 'area'), ...
    'stats.size.hist should not expose area histograms when size statistics use diameter only.');
assertTrue(~isfield(outSizeStats.stats.size.pore.hist, 'radius'), ...
    'stats.size.hist should not expose radius histograms when size statistics use diameter only.');
assertTrue(sum(outSizeStats.stats.size.pore.hist.diameter.count) == 2, ...
    'Diameter histogram should count both pore components.');

networkDiameterPlotRange = [1.0 1.8];
outSizeHistBins = analyze_chunk_network2d(sizeStatsPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', true, ...
    'DiameterHistBinSize', 0.2, ...
    'DiameterPlotRange', networkDiameterPlotRange);
assertApprox(max(abs(diff(outSizeHistBins.pore.equivDiameterDistribution.edges) - 0.2)), ...
    0, 1e-12, 'Network DiameterHistBinSize should control legacy diameter count bins.');
assertApprox(max(abs(diff(outSizeHistBins.stats.size.pore.hist.diameter.edges) - 0.2)), ...
    0, 1e-12, 'Network stats.size.hist.diameter should use DiameterHistBinSize.');
networkCountAxes = getFigureDataAxes(outSizeHistBins.plots.poreCountFig);
assertArrayApprox(get(networkCountAxes(1), 'XLim'), networkDiameterPlotRange, 1e-12, ...
    'Network DiameterPlotRange should crop pore diameter count plots.');
closeHandles(collectPlotHandles(outSizeHistBins.plots));

outBranch = analyze_chunk_network2d(branchPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, 'EnableSkeletonGraph', true);
assertTrue(outBranch.stats.network.pore.enabled == 1, ...
    'Skeleton graph should report enabled=true when requested.');
assertTrue(outBranch.stats.network.pore.branchPoints == 1, ...
    'Plus-shaped pore skeleton should contain one branch point.');
assertTrue(outBranch.stats.network.pore.endPoints == 4, ...
    'Plus-shaped pore skeleton should contain four endpoints.');
assertTrue(outBranch.stats.network.pore.skeletonLength > 0, ...
    'Skeleton length should be positive for a connected pore network.');

outNeck = analyze_chunk_network2d(neckPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false);
assertApprox(outNeck.stats.thickness.matrix.min, 2, 1e-12, ...
    'One-pixel matrix neck should have minimum thickness 2*distance = 2.');
assertTrue(outNeck.stats.thickness.matrix.mean > outNeck.stats.thickness.matrix.min, ...
    'Matrix thickness mean should exceed the narrowest neck thickness.');
assertTrue(outNeck.stats.thickness.matrix.p5 >= outNeck.stats.thickness.matrix.min, ...
    'Low-percentile thickness should stay above or equal to the minimum thickness.');

outFragment = analyze_chunk_network2d(fragmentPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false);
assertTrue(outFragment.stats.fragmentation.matrix.count == 4, ...
    'Four isolated matrix cells should produce four fragments.');
assertTrue(outFragment.stats.fragmentation.matrix.count == outFragment.stats.topology.matrix.beta0, ...
    'Fragment count should match matrix beta0.');
assertApprox(outFragment.stats.fragmentation.matrix.largestFraction, 0.25, 1e-12, ...
    'Largest fragment fraction should match the four-equal-island case.');
assertTrue(sum(outFragment.stats.fragmentation.matrix.sizeDist.count) == 4, ...
    'Fragment size histogram should count every matrix fragment.');
assertArrayApprox(outFragment.stats.fragmentation.matrix.sizeDist.edges(:), ...
    outFragment.stats.size.matrix.hist.diameter.edges(:), 1e-12, ...
    'Fragmentation sizeDist should reuse the matrix diameter histogram.');

outEvolution = analyze_chunk_network2d(evolutionPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, ...
    'EnableEvolution', true, 'EvolutionSelectBy', 'TimeStep', ...
    'EvolutionRange', [100 400], 'EvolutionStride', 1);
assertArrayApprox(outEvolution.stats.evolution.timestep(:), [100; 200; 300; 400], 1e-12, ...
    'Evolution scan should preserve timestep order inside the selected range.');
assertArrayApprox(outEvolution.stats.evolution.topology.pore.beta0(:), [2; 1; 1; 1], 1e-12, ...
    'Evolution scan should capture pore-component merging.');
assertArrayApprox(outEvolution.stats.evolution.topology.pore.beta1(:), [0; 0; 1; 0], 1e-12, ...
    'Evolution scan should capture pore loop formation and loss.');
assertArrayApprox(outEvolution.stats.evolution.connectivity.pore.largestFraction(:), [0.5; 1; 1; 1], 1e-12, ...
    'Evolution scan should capture the largest pore-cluster jump.');
assertArrayApprox(outEvolution.stats.evolution.topology.matrix.beta0(:), [1; 1; 1; 2], 1e-12, ...
    'Evolution scan should capture matrix fragmentation.');
assertArrayApprox(outEvolution.stats.evolution.transition.pore.deltaBeta0(:), [NaN; -1; 0; 0], 1e-12, ...
    'Evolution transitions should include pore deltaBeta0.');
assertArrayApprox(outEvolution.stats.evolution.transition.matrix.deltaBeta0(:), [NaN; 0; 0; 1], 1e-12, ...
    'Evolution transitions should include matrix deltaBeta0.');

outEvolutionStride = analyze_chunk_network2d(evolutionPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', false, ...
    'EnableEvolution', true, 'EvolutionSelectBy', 'TimeStep', ...
    'EvolutionRange', [100 400], 'EvolutionStride', 2);
assertArrayApprox(outEvolutionStride.stats.evolution.timestep(:), [100; 300], 1e-12, ...
    'EvolutionStride should sub-sample the selected timestep range.');

outNetworkPlot = analyze_chunk_network2d(ringPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', true, 'PositionAxis', 'both', ...
    'ProfileAxis', 'both', 'ProfileNumBins', 3);
assertTrue(ishandle(outNetworkPlot.plots.phaseFig), ...
    'phaseFig should be returned when MakePlots=true.');
assertTrue(ishandle(outNetworkPlot.plots.poreLabelFig), ...
    'poreLabelFig should be returned when MakePlots=true.');
assertTrue(ishandle(outNetworkPlot.plots.matrixLabelFig), ...
    'matrixLabelFig should be returned when MakePlots=true.');
assertTrue(ishandle(outNetworkPlot.plots.connectivityFig), ...
    'connectivityFig should be returned when MakePlots=true.');
assertTrue(ishandle(outNetworkPlot.plots.profileFigX), ...
    'profileFigX should be returned when ProfileAxis includes x.');
assertTrue(ishandle(outNetworkPlot.plots.profileFigY), ...
    'profileFigY should be returned when ProfileAxis includes y.');
assertTrue(ishandle(outNetworkPlot.plots.poreCountFig), ...
    'poreCountFig should be returned when MakePlots=true.');
assertTrue(isempty(outNetworkPlot.plots.poreProbFig), ...
    'poreProbFig should stay empty after probability plots were removed.');
assertTrue(isempty(outNetworkPlot.plots.poreCdfFig), ...
    'poreCdfFig should stay empty after CDF plots were removed.');
assertTrue(ishandle(outNetworkPlot.plots.porePositionFigX), ...
    'porePositionFigX should be returned when PositionAxis includes x.');
assertTrue(ishandle(outNetworkPlot.plots.porePositionFigY), ...
    'porePositionFigY should be returned when PositionAxis includes y.');
assertTrue(ishandle(outNetworkPlot.plots.matrixCountFig), ...
    'matrixCountFig should be returned when MakePlots=true.');
assertTrue(isempty(outNetworkPlot.plots.matrixProbFig), ...
    'matrixProbFig should stay empty after probability plots were removed.');
assertTrue(isempty(outNetworkPlot.plots.matrixCdfFig), ...
    'matrixCdfFig should stay empty after CDF plots were removed.');
assertTrue(ishandle(outNetworkPlot.plots.matrixPositionFigX), ...
    'matrixPositionFigX should be returned when PositionAxis includes x.');
assertTrue(ishandle(outNetworkPlot.plots.matrixPositionFigY), ...
    'matrixPositionFigY should be returned when PositionAxis includes y.');
closeHandles(collectPlotHandles(outNetworkPlot.plots));

plotRangeX = [0.5 1.5];
plotRangeY = [0.25 1.75];
outNetworkPlotRange = analyze_chunk_network2d(ringPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', true, ...
    'PlotRangeX', plotRangeX, 'PlotRangeY', plotRangeY);
assertArrayApprox(outNetworkPlotRange.plotRange.x(:), plotRangeX(:), 1e-12, ...
    'plotRange.x should record the requested x cropping range.');
assertArrayApprox(outNetworkPlotRange.plotRange.y(:), plotRangeY(:), 1e-12, ...
    'plotRange.y should record the requested y cropping range.');

phaseAxes = getFigureDataAxes(outNetworkPlotRange.plots.phaseFig);
assertTrue(numel(phaseAxes) == 1, ...
    'phaseFig should expose one main plotting axis after removing the colorbar axis.');
assertArrayApprox(get(phaseAxes(1), 'XLim'), plotRangeX, 1e-12, ...
    'PlotRangeX should crop the 2D phase figure.');
assertArrayApprox(get(phaseAxes(1), 'YLim'), plotRangeY, 1e-12, ...
    'PlotRangeY should crop the 2D phase figure.');

labelAxes = getFigureDataAxes(outNetworkPlotRange.plots.poreLabelFig);
assertTrue(numel(labelAxes) == 1, ...
    'poreLabelFig should expose one main plotting axis after removing the colorbar axis.');
assertArrayApprox(get(labelAxes(1), 'XLim'), plotRangeX, 1e-12, ...
    'PlotRangeX should crop the pore label figure.');
assertArrayApprox(get(labelAxes(1), 'YLim'), plotRangeY, 1e-12, ...
    'PlotRangeY should crop the pore label figure.');

connectivityAxes = getFigureDataAxes(outNetworkPlotRange.plots.connectivityFig);
assertTrue(numel(connectivityAxes) == 4, ...
    'connectivityFig should expose four subplot axes.');
for iAx = 1:numel(connectivityAxes)
    assertArrayApprox(get(connectivityAxes(iAx), 'XLim'), plotRangeX, 1e-12, ...
        'PlotRangeX should crop every connectivity subplot.');
    assertArrayApprox(get(connectivityAxes(iAx), 'YLim'), plotRangeY, 1e-12, ...
        'PlotRangeY should crop every connectivity subplot.');
end
closeHandles(collectPlotHandles(outNetworkPlotRange.plots));

outLabelRankPlot = analyze_chunk_network2d(labelRankPath, ...
    'SelectBy', 'Index', 'Index', 1, 'ProgressMode', 'off', ...
    'ThresholdN', 1, 'MakePlots', true);
rankInfo = get(outLabelRankPlot.plots.poreLabelFig, 'UserData');
assertArrayApprox(rankInfo.label(:), [2; 1], 1e-12, ...
    'Pore label colors should be assigned by descending component size, not raw label order.');
rankAxes = getFigureDataAxes(outLabelRankPlot.plots.poreLabelFig);
rankImage = findall(rankAxes(1), 'Type', 'image');
rankCData = get(rankImage(1), 'CData');
assertApprox(rankCData(3, 2), 1, 1e-12, ...
    'The largest pore component should receive size rank 1 in the label plot.');
assertApprox(rankCData(1, 1), 2, 1e-12, ...
    'The smaller pore component should receive a later size rank in the label plot.');
rankCmap = colormap(rankAxes(1));
matrixPhaseColor = [0.20 0.45 0.80];
componentColors = rankCmap(2:end, :);
distFromMatrixColor = max(abs(componentColors - repmat(matrixPhaseColor, size(componentColors, 1), 1)), [], 2);
assertTrue(all(distFromMatrixColor > 1e-3), ...
    'Size-ranked pore component colors should avoid the matrix phase color.');
closeHandles(collectPlotHandles(outLabelRankPlot.plots));

fprintf('RUN_NETWORK2D|porosity=%.6f|interface=%.6f|poreComponents=%d|matrixHoleCount=%d\n', ...
    outNetwork.global.porosity, outNetwork.global.interfaceLength, ...
    outNetwork.pore.numComponents, outNetwork.matrix.holeCount);
fprintf(logFid, 'RUN_NETWORK2D|porosity=%.6f|interface=%.6f|poreComponents=%d|matrixHoleCount=%d\n', ...
    outNetwork.global.porosity, outNetwork.global.interfaceLength, ...
    outNetwork.pore.numComponents, outNetwork.matrix.holeCount);

fprintf('SELFTEST_OK\n');
fprintf(logFid, 'SELFTEST_OK\n');
fclose(logFid);

function assertTrue(cond, msg)
if ~cond
    error('selftest:AssertionFailed', '%s', msg);
end
end

function assertApprox(actual, expected, tol, msg)
if nargin < 4
    msg = 'Values are not within tolerance.';
end
if ~(isfinite(actual) && isfinite(expected) && abs(actual - expected) <= tol)
    error('selftest:AssertionFailed', '%s (actual=%g, expected=%g, tol=%g)', ...
        msg, actual, expected, tol);
end
end

function assertArrayApprox(actual, expected, tol, msg)
if nargin < 4
    msg = 'Arrays are not within tolerance.';
end
if ~isequal(size(actual), size(expected))
    error('selftest:AssertionFailed', '%s (size mismatch).', msg);
end
sameNaN = isequal(isnan(actual), isnan(expected));
if ~sameNaN
    error('selftest:AssertionFailed', '%s (NaN mask mismatch).', msg);
end
mask = isfinite(actual) & isfinite(expected);
if any(mask(:))
    maxErr = max(abs(actual(mask) - expected(mask)));
else
    maxErr = 0;
end
if maxErr > tol
    error('selftest:AssertionFailed', '%s (maxErr=%g, tol=%g)', msg, maxErr, tol);
end
end

function assertContainsText(txt, pattern, msg)
if isempty(strfind(txt, pattern))
    error('selftest:AssertionFailed', '%s (missing pattern: %s)', msg, pattern);
end
end

function expectError(fun, expectedId)
try
    fun();
catch ME
    if strcmp(ME.identifier, expectedId)
        return;
    end
    error('selftest:UnexpectedError', ...
        'Expected error %s but got %s (%s).', expectedId, ME.identifier, ME.message);
end
error('selftest:MissingExpectedError', 'Expected error %s was not raised.', expectedId);
end

function meanVals = computeBinnedMomentMeans(x, d, edges, meanPowerM, meanPowerN)
binId = discretize(x, edges);
meanVals = nan(1, numel(edges)-1);
for i = 1:numel(meanVals)
    idx = (binId == i);
    if any(idx)
        meanVals(i) = sum(d(idx) .^ meanPowerM) / sum(d(idx) .^ meanPowerN);
    end
end
end

function cleanupTempDir(dirPath)
if exist(dirPath, 'dir')
    try
        rmdir(dirPath, 's');
    catch
        % ignore cleanup failures
    end
end
end

function restoreFigureVisible(oldValue)
try
    set(0, 'DefaultFigureVisible', oldValue);
catch
    % ignore restore failures
end
end

function writeChunk2dCase(filePath, ncountGrid, timestep)
if nargin < 3
    timestep = 100;
end
fid = fopen(filePath, 'w');
if fid < 0
    error('selftest:FileOpenFail', 'Cannot open %s for writing.', filePath);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '# selftest chunk header 1\n');
fprintf(fid, '# selftest chunk header 2\n');
fprintf(fid, '# Chunk Coord1 Coord2 Ncount\n');
fprintf(fid, '%g %d %g\n', timestep, numel(ncountGrid), sum(ncountGrid(:)));
chunkId = 1;
for iy = 1:size(ncountGrid, 1)
    for ix = 1:size(ncountGrid, 2)
        fprintf(fid, '%d %g %g %g\n', chunkId, ix - 1, iy - 1, ncountGrid(iy, ix));
        chunkId = chunkId + 1;
    end
end
end

function writeChunk1dCase(filePath, ncountLine, timestep)
if nargin < 3
    timestep = 100;
end
fid = fopen(filePath, 'w');
if fid < 0
    error('selftest:FileOpenFail', 'Cannot open %s for writing.', filePath);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '# selftest chunk header 1\n');
fprintf(fid, '# selftest chunk header 2\n');
fprintf(fid, '# Chunk Coord1 Ncount\n');
fprintf(fid, '%g %d %g\n', timestep, numel(ncountLine), sum(ncountLine(:)));
for ix = 1:numel(ncountLine)
    fprintf(fid, '%d %g %g\n', ix, ix - 1, ncountLine(ix));
end
end

function writeChunk2dStepsCase(filePath, ncountGrids, timesteps)
if numel(ncountGrids) ~= numel(timesteps)
    error('selftest:BadMultiStepInput', 'ncountGrids and timesteps must have the same length.');
end
fid = fopen(filePath, 'w');
if fid < 0
    error('selftest:FileOpenFail', 'Cannot open %s for writing.', filePath);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '# selftest chunk header 1\n');
fprintf(fid, '# selftest chunk header 2\n');
fprintf(fid, '# Chunk Coord1 Coord2 Ncount\n');
for s = 1:numel(ncountGrids)
    grid = ncountGrids{s};
    fprintf(fid, '%g %d %g\n', timesteps(s), numel(grid), sum(grid(:)));
    chunkId = 1;
    for iy = 1:size(grid, 1)
        for ix = 1:size(grid, 2)
            fprintf(fid, '%d %g %g %g\n', chunkId, ix - 1, iy - 1, grid(iy, ix));
            chunkId = chunkId + 1;
        end
    end
end
end

function handles = collectPlotHandles(plotStruct)
names = fieldnames(plotStruct);
handles = [];
for i = 1:numel(names)
    h = plotStruct.(names{i});
    if isempty(h)
        continue;
    end
    handles = [handles; h(:)]; %#ok<AGROW>
end
end

function axesHandles = getFigureDataAxes(fig)
axesHandles = findall(fig, 'Type', 'axes');
keep = true(size(axesHandles));
for i = 1:numel(axesHandles)
    tag = get(axesHandles(i), 'Tag');
    keep(i) = ~strcmp(tag, 'Colorbar');
end
axesHandles = axesHandles(keep);
end

function closeHandles(handles)
if isempty(handles)
    return;
end
valid = [];
for i = 1:numel(handles)
    if ishandle(handles(i))
        valid(end+1) = handles(i); %#ok<AGROW>
    end
end
if ~isempty(valid)
    close(valid);
end
end
