function catalog = pd_option_catalog(analysisType)
%PD_OPTION_CATALOG Complete editable option metadata for each analysis.
% MATLAB R2016b compatible. GUI and scripts share this single definition.

    analysisType = pd_normalize_analysis_type(analysisType);
    switch analysisType
        case 'chunk'
            catalog = [ ...
                item('ChunkDim', 'auto', 'text', 'chunk.dimension', 'auto, 1d, 2d, or 3d'), ...
                item('Variable', 'c_rho', 'text', 'chunk.variable', 'Raw or derived field name'), ...
                item('dV', [], 'numeric', 'chunk.dV', 'Cell volume for MD-derived density, pressure, and stress; unused by raw SPH fields'), ...
                item('CoordScale', 1, 'numeric', 'chunk.coordScale', 'Coordinate scale factor'), ...
                item('CoordRangeX', [], 'numeric', 'chunk.coordRangeX', 'X range [min max]'), ...
                item('CoordRangeY', [], 'numeric', 'chunk.coordRangeY', 'Y range [min max]'), ...
                item('CoordRangeZ', [], 'numeric', 'chunk.coordRangeZ', 'Z range [min max]'), ...
                item('GradientVariable', '', 'text', 'chunk.gradientVariable', 'Target field for Variable=gradient'), ...
                item('GradientSmoothLevel', 0, 'numeric', 'chunk.gradientSmoothLevel', 'Gaussian smoothing sigma before 1D differentiation'), ...
                item('StrainRateVelocityComponent', 'vz', 'text', 'chunk.strainRateVelocityComponent', 'Velocity field used by 1D strain rate'), ...
                item('StrainRateDensityVariable', 'c_rho', 'text', 'chunk.strainRateDensityVariable', 'Density field used by 1D strain rate')];

        case 'cluster'
            catalog = [ ...
                item('Dim', 2, 'numeric', 'analysis', 'Spatial dimension: 2 or 3'), ...
                item('Dx', 1, 'numeric', 'analysis', 'Particle spacing'), ...
                item('ParticleVolume', [], 'numeric', 'analysis', 'Explicit per-particle volume for Dim=3'), ...
                item('ThinDirectionThickness', [], 'numeric', 'analysis', 'Thickness for quasi-2D projection'), ...
                item('NcountVar', 'Ncount', 'text', 'analysis', 'Cluster count column'), ...
                item('Range_c_x', [], 'numeric', 'analysis', 'Centroid X range'), ...
                item('Range_c_y', [], 'numeric', 'analysis', 'Centroid Y range'), ...
                item('Range_c_z', [], 'numeric', 'analysis', 'Centroid Z range'), ...
                item('Range_vx', [], 'numeric', 'analysis', 'Velocity X range'), ...
                item('Range_vy', [], 'numeric', 'analysis', 'Velocity Y range'), ...
                item('Range_vz', [], 'numeric', 'analysis', 'Velocity Z range'), ...
                item('DiameterRange', [], 'numeric', 'analysis', 'Equivalent diameter range'), ...
                item('XVarForMean', 'c_x', 'text', 'analysis', 'Variable used for binned means'), ...
                item('MeanNumBins', 20, 'numeric', 'analysis', 'Number of position bins'), ...
                item('MeanPowerM', 1, 'numeric', 'analysis', 'Generalized mean numerator power'), ...
                item('MeanPowerN', 0, 'numeric', 'analysis', 'Generalized mean denominator power'), ...
                item('DiameterHistBinSize', [], 'numeric', 'analysis', 'Diameter histogram bin width'), ...
                item('DiameterEmptyBinMode', 'zero', 'text', 'analysis', 'zero, nan, or remove'), ...
                item('DiameterPlotStyle', 'bar', 'text', 'analysis', 'bar or scatter'), ...
                item('DiameterFitTypes', {'powerlaw','gamma','lognormal'}, 'celltext', 'analysis', 'Comma-separated fit types'), ...
                item('HistScale', 'linear', 'text', 'analysis', 'linear, semilogx, semilogy, or loglog')];

        case 'vx'
            catalog = [ ...
                item('VelocityVar', 'auto', 'text', 'analysis', 'auto tries Coord1 then Chunk'), ...
                item('VelocityFactor', 0.001, 'numeric', 'analysis', 'Manual coordinate-to-km/s factor'), ...
                item('DensityFactor', 1, 'numeric', 'analysis', 'Manual areal-density-to-mg/cm^2 factor'), ...
                item('UseFileUnitMetadata', true, 'logical', 'analysis', 'Use SPID Units metadata when available'), ...
                item('VelocityLabel', 'Velocity', 'text', 'analysis', 'Velocity axis label'), ...
                item('VelocityUnit', 'km/s', 'text', 'analysis', 'Velocity axis unit'), ...
                item('CumulativeDirection', 'high-to-low', 'text', 'analysis', 'high-to-low or low-to-high'), ...
                item('NegativeDensityMode', 'clip', 'text', 'analysis', 'clip or reject negative areal-density values'), ...
                item('DensityVars', {}, 'celltext', 'analysis', 'Comma-separated density columns; empty means auto')];

        case 'massx'
            catalog = [ ...
                item('ChunkDim', 'auto', 'text', 'analysis', 'SPH chunk dimension: auto, 1d, or 2d'), ...
                item('CoordinateVar', 'auto', 'text', 'analysis', 'Coordinate column; auto tries Coord1, c_x, then Chunk'), ...
                item('CoordinateVarY', 'auto', 'text', 'analysis', 'Y column for bin2d; auto tries Coord2 then c_y'), ...
                item('NcountVar', 'Ncount', 'text', 'analysis', 'SPH particle-count column'), ...
                item('SphDimension', 2, 'numeric', 'analysis', 'Physical SPH dimension: 2 or 3'), ...
                item('InitialDensity', [], 'numeric', 'analysis', 'Initial SPH material density in g/cm^3'), ...
                item('ParticleSpacing', [], 'numeric', 'analysis', 'Initial SPH particle spacing d0 in raw coordinate units'), ...
                item('RawLengthUnitUm', 10, 'numeric', 'analysis', 'Physical micrometers represented by one raw coordinate unit'), ...
                item('UseFileUnitMetadata', true, 'logical', 'analysis', 'Use SPID Units metadata when available'), ...
                item('TransverseWidth', [], 'numeric', 'analysis', 'Full y width in raw units; required for bin1d'), ...
                item('OutOfPlaneWidth', [], 'numeric', 'analysis', 'Full z width in raw units; required for 3D SPH'), ...
                item('SliceCentersY', [], 'numeric', 'analysis', 'Optional bin2d y-slice centers in raw units'), ...
                item('SliceWidthsY', [], 'numeric', 'analysis', 'Scalar or per-slice bin2d y widths in raw units'), ...
                item('CoordinateFactor', 10, 'numeric', 'analysis', 'Display coordinate multiplier; normally 10 for um'), ...
                item('CoordinateRange', [], 'numeric', 'analysis', 'Coordinate range after conversion [min max]'), ...
                item('CoordinateLabel', 'x', 'text', 'analysis', 'Coordinate axis label'), ...
                item('CoordinateUnit', 'um', 'text', 'analysis', 'Coordinate unit shown on plots'), ...
                item('CumulativeDirection', 'high-to-low', 'text', 'analysis', 'Fixed high-to-low so cumulative mass-x decreases with x')];

        case 'network2d'
            catalog = [ ...
                item('ThresholdN', 1, 'numeric', 'analysis', 'Pore when Ncount is below this value'), ...
                item('Connectivity', 4, 'numeric', 'analysis', 'Foreground connectivity'), ...
                item('Boundary', 'open', 'text', 'analysis', 'open, periodic-x, periodic-y, or periodic-xy'), ...
                item('Dx', [], 'numeric', 'analysis', 'Grid spacing X; empty means infer'), ...
                item('Dy', [], 'numeric', 'analysis', 'Grid spacing Y; empty means infer'), ...
                item('CoordScale', 1, 'numeric', 'chunk.coordScale', 'Coordinate scale factor'), ...
                item('NcountVar', 'Ncount', 'text', 'analysis', 'Count column name'), ...
                item('PositionAxis', 'x', 'text', 'analysis', 'x, y, or both'), ...
                item('PositionNumBins', 20, 'numeric', 'analysis', 'Component-position bins'), ...
                item('PositionRangeX', [], 'numeric', 'analysis', 'Component X range'), ...
                item('PositionRangeY', [], 'numeric', 'analysis', 'Component Y range'), ...
                item('PlotRangeX', [], 'numeric', 'analysis', 'Computed plot X range'), ...
                item('PlotRangeY', [], 'numeric', 'analysis', 'Computed plot Y range'), ...
                item('ProfileAxis', 'x', 'text', 'analysis', 'x, y, or both'), ...
                item('ProfileNumBins', 20, 'numeric', 'analysis', 'Directional profile bins'), ...
                item('ProfileRangeX', [], 'numeric', 'analysis', 'Profile X range'), ...
                item('ProfileRangeY', [], 'numeric', 'analysis', 'Profile Y range'), ...
                item('DiameterRange', [], 'numeric', 'analysis', 'Component diameter range'), ...
                item('DiameterHistBinSize', [], 'numeric', 'analysis', 'Diameter histogram bin width'), ...
                item('DiameterEmptyBinMode', 'zero', 'text', 'analysis', 'zero, nan, or remove'), ...
                item('DiameterPlotStyle', 'bar', 'text', 'analysis', 'bar or scatter'), ...
                item('DiameterFitTypes', {'powerlaw','gamma','lognormal'}, 'celltext', 'analysis', 'Comma-separated fit types'), ...
                item('HistScale', 'linear', 'text', 'analysis', 'Histogram axis scale'), ...
                item('MeanPowerM', 1, 'numeric', 'analysis', 'Generalized mean numerator power'), ...
                item('MeanPowerN', 0, 'numeric', 'analysis', 'Generalized mean denominator power'), ...
                item('GeometryMode', 'cutcell', 'text', 'analysis', 'cutcell or original'), ...
                item('CutCellMethod', 'plic', 'text', 'analysis', 'Cut-cell reconstruction method'), ...
                item('CutCellFallback', 'binary', 'text', 'analysis', 'binary or error'), ...
                item('CutCellPlotRefinement', 4, 'numeric', 'analysis', 'Display refinement factor'), ...
                item('EnableSkeletonGraph', false, 'logical', 'analysis', 'Enable skeleton and thickness metrics'), ...
                item('EnableEvolution', false, 'logical', 'analysis', 'Scan multiple steps'), ...
                item('EvolutionSelectBy', '', 'text', 'analysis', 'Index, TimeStep, Time, or empty'), ...
                item('EvolutionRange', [], 'numeric', 'analysis', 'Evolution range [min max]'), ...
                item('EvolutionStride', 1, 'numeric', 'analysis', 'Evolution step stride')];

        otherwise
            error('postdata:UnknownAnalysisType', 'Unknown analysis type: %s', analysisType);
    end
    catalog = applyRules(catalog, analysisType);
end

function value = item(name, defaultValue, typeName, target, description)
    value = struct();
    value.Name = name;
    value.Default = defaultValue;
    value.Type = typeName;
    value.Target = target;
    value.Description = description;
    value.AllowedValues = {};
    value.Minimum = [];
    value.ExclusiveMinimum = false;
    value.Maximum = [];
    value.IntegerOnly = false;
    value.Required = false;
    value.VectorLength = [];
    value.DependsOn = '';
    value.DependsValue = [];
end

function catalog = applyRules(catalog, analysisType)
    switch analysisType
        case 'chunk'
            catalog = rule(catalog, 'ChunkDim', 'AllowedValues', {'auto','1d','2d','3d'}, 'Required', true);
            catalog = rule(catalog, 'Variable', 'Required', true);
            catalog = rule(catalog, 'dV', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'CoordScale', 'Minimum', 0, 'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'GradientSmoothLevel', 'Minimum', 0, 'Required', true);
            catalog = rule(catalog, 'StrainRateVelocityComponent', 'Required', true);
            catalog = rule(catalog, 'StrainRateDensityVariable', 'Required', true);
            catalog = rangeRules(catalog, {'CoordRangeX','CoordRangeY','CoordRangeZ'});
        case 'cluster'
            catalog = rule(catalog, 'Dim', 'AllowedValues', {'2','3'}, 'IntegerOnly', true);
            catalog = rule(catalog, 'Dx', 'Minimum', 0, 'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'ParticleVolume', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'ThinDirectionThickness', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'NcountVar', 'Required', true);
            catalog = rangeRules(catalog, {'Range_c_x','Range_c_y','Range_c_z', ...
                'Range_vx','Range_vy','Range_vz','DiameterRange'});
            catalog = rule(catalog, 'MeanNumBins', 'Minimum', 1, 'IntegerOnly', true);
            catalog = rule(catalog, 'DiameterHistBinSize', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'DiameterEmptyBinMode', 'AllowedValues', {'zero','nan','remove'});
            catalog = rule(catalog, 'DiameterPlotStyle', 'AllowedValues', {'bar','scatter'});
            catalog = rule(catalog, 'HistScale', 'AllowedValues', {'linear','semilogx','semilogy','loglog'});
        case 'vx'
            catalog = rule(catalog, 'VelocityFactor', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'DensityFactor', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'VelocityVar', 'Required', true);
            catalog = rule(catalog, 'VelocityLabel', 'Required', true);
            catalog = rule(catalog, 'VelocityUnit', 'Required', true);
            catalog = rule(catalog, 'CumulativeDirection', 'AllowedValues', ...
                {'high-to-low','low-to-high'}, 'Required', true);
            catalog = rule(catalog, 'NegativeDensityMode', 'AllowedValues', ...
                {'clip','error'}, 'Required', true);
        case 'massx'
            catalog = rule(catalog, 'ChunkDim', 'AllowedValues', ...
                {'auto','1d','2d'}, 'Required', true);
            catalog = rule(catalog, 'SphDimension', 'AllowedValues', ...
                {'2','3'}, 'IntegerOnly', true, 'Required', true);
            catalog = rule(catalog, 'CoordinateFactor', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'RawLengthUnitUm', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'InitialDensity', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'ParticleSpacing', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'TransverseWidth', 'Minimum', 0, ...
                'ExclusiveMinimum', true);
            catalog = rule(catalog, 'OutOfPlaneWidth', 'Minimum', 0, ...
                'ExclusiveMinimum', true, 'DependsOn', 'SphDimension', ...
                'DependsValue', 3);
            catalog = rule(catalog, 'SliceWidthsY', 'Minimum', 0, ...
                'ExclusiveMinimum', true);
            catalog = rangeRules(catalog, {'CoordinateRange'});
            catalog = rule(catalog, 'CoordinateVar', 'Required', true);
            catalog = rule(catalog, 'CoordinateVarY', 'Required', true);
            catalog = rule(catalog, 'NcountVar', 'Required', true);
            catalog = rule(catalog, 'CoordinateLabel', 'Required', true);
            catalog = rule(catalog, 'CoordinateUnit', 'Required', true);
            catalog = rule(catalog, 'CumulativeDirection', 'AllowedValues', ...
                {'high-to-low'}, 'Required', true);
        case 'network2d'
            catalog = rule(catalog, 'ThresholdN', 'Required', true);
            catalog = rule(catalog, 'Connectivity', 'AllowedValues', {'4'}, 'IntegerOnly', true);
            catalog = rule(catalog, 'Boundary', 'AllowedValues', ...
                {'open','periodic-x','periodic-y','periodic-xy'});
            catalog = rule(catalog, 'Dx', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'Dy', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'CoordScale', 'Minimum', 0, 'ExclusiveMinimum', true, 'Required', true);
            catalog = rule(catalog, 'NcountVar', 'Required', true);
            catalog = rule(catalog, 'PositionAxis', 'AllowedValues', {'x','y','both'});
            catalog = rule(catalog, 'PositionNumBins', 'Minimum', 1, 'IntegerOnly', true);
            catalog = rule(catalog, 'ProfileAxis', 'AllowedValues', {'x','y','both'});
            catalog = rule(catalog, 'ProfileNumBins', 'Minimum', 1, 'IntegerOnly', true);
            catalog = rangeRules(catalog, {'PositionRangeX','PositionRangeY','PlotRangeX', ...
                'PlotRangeY','ProfileRangeX','ProfileRangeY','DiameterRange','EvolutionRange'});
            catalog = rule(catalog, 'DiameterHistBinSize', 'Minimum', 0, 'ExclusiveMinimum', true);
            catalog = rule(catalog, 'DiameterEmptyBinMode', 'AllowedValues', {'zero','nan','remove'});
            catalog = rule(catalog, 'DiameterPlotStyle', 'AllowedValues', {'bar','scatter'});
            catalog = rule(catalog, 'HistScale', 'AllowedValues', {'linear','semilogx','semilogy','loglog'});
            catalog = rule(catalog, 'GeometryMode', 'AllowedValues', {'cutcell','original'});
            catalog = rule(catalog, 'CutCellMethod', 'AllowedValues', {'plic'}, ...
                'DependsOn', 'GeometryMode', 'DependsValue', 'cutcell');
            catalog = rule(catalog, 'CutCellFallback', 'AllowedValues', {'binary','error'}, ...
                'DependsOn', 'GeometryMode', 'DependsValue', 'cutcell');
            catalog = rule(catalog, 'CutCellPlotRefinement', 'Minimum', 1, 'IntegerOnly', true, ...
                'DependsOn', 'GeometryMode', 'DependsValue', 'cutcell');
            catalog = rule(catalog, 'EvolutionSelectBy', 'AllowedValues', {'','Index','TimeStep','Time'}, ...
                'DependsOn', 'EnableEvolution', 'DependsValue', true);
            catalog = rule(catalog, 'EvolutionRange', 'DependsOn', 'EnableEvolution', 'DependsValue', true);
            catalog = rule(catalog, 'EvolutionStride', 'Minimum', 1, 'IntegerOnly', true, ...
                'DependsOn', 'EnableEvolution', 'DependsValue', true);
    end
end

function catalog = rangeRules(catalog, names)
    for i = 1:numel(names)
        catalog = rule(catalog, names{i}, 'VectorLength', 2);
    end
end

function catalog = rule(catalog, name, varargin)
    index = find(strcmp(name, {catalog.Name}), 1, 'first');
    if isempty(index), error('postdata:MissingCatalogRuleTarget', 'Unknown option %s.', name); end
    for i = 1:2:numel(varargin)
        catalog(index).(varargin{i}) = varargin{i + 1};
    end
end
